from pathlib import Path
import json, subprocess, hashlib, csv
ROOT=Path(__file__).resolve().parents[2]
OUT=Path(__file__).resolve().parent
items=[]
def add(id,group,title,status,mechanism,code,evidence,boundary):
    items.append(dict(id=id,group=group,title=title,status=status,mechanism=mechanism,code=code,evidence=evidence,boundary=boundary))
# code entries are (path, exact substring); line positions are resolved against the audited working tree.
F='include/framework/framework.cuh'; S='include/groute/graphs/source_local_chunk_store.h'; R='include/framework/dynamic_reverse_index.h'; G='include/groute/graphs/csr_graph.cuh'; U='include/framework/effective_update_batch.h'; O='include/framework/ordered_gpu_repair.cuh'; D='include/framework/variants/driver.cuh'; P='include/framework/variants/push_functor.h'; H='samples/hybrid_sssp/hybrid_sssp.cu'
plan='iteration/cggraph_cpu_gpu_dev_implementation_plan.md'
add('A01','当前拓扑与发布','CPU 权威的 source-local 连续邻接存储（C1–C3）','当前主路径','把全局 PMA 的跨 source relocation 改为按 source 隔离的连续 chunk；mapped-pinned slab、host descriptor、device slab pointer 和兼容遍历视图配合，未更新 source 的邻接与 descriptor 不因其它 source 更新移动。冷邻接可经映射主存访问；这不是新增全图 GPU CSR。',[(S,'class SourceLocalChunkStore'),(G,'void BindChunkStore'),('include/groute/graphs/topology_contract.cuh','struct ContiguousAdjacencyView')],f'{plan} §C1–C3；src/chunk_store_replay.cpp；tests/source_local_chunk_store_test.cpp。C2 三图首批 capacity amplification 1.455/1.430/1.453×，属于结构证据。','原版已有 host PMA、Zero-Copy、hot cache；贡献是更新隔离与权威拓扑/发布组织，不是发明 Zero-Copy。存储仍有初始化 O(V+E) 成本及固定 arena 容量。')
add('A02','当前拓扑与发布','chunk 容量预检、块复用与 epoch 延迟回收（C2/D3/I10）','当前主路径','整批先模拟可用 free block/slab 容量，成功后分配；扩容旧块进入 retired 列表，完成相应 epoch 后回收；arena 统计检查 live/free/retired/high-water 守恒。',[(S,'void EnsureAllocationsFit'),(S,'Allocation Allocate'),(S,'uint64_t ReclaimThrough'),('tests/source_local_chunk_store_test.cpp','int main')],f'{plan} §C2、D3、I10；Wiki 十批约复用 1.5K–1.6K retired blocks/batch，high-water 465.97→468.26 MB。','预检失败的可见拓扑不变有测试，不等于任意硬件/内部 invariant 失败下的通用事务回滚；不是在线无界增长的 arena。')
add('A03','当前拓扑与发布','稳定 occurrence 删除与两遍计划/单次 compact、直接 rewrite（D3）','当前主路径','先计数匹配实际删除 occurrence、final degree、扩容需求；单删除直接 first-match+一次 memmove，多删除按 run 计数稳定 compact；足容 addition-only 直接 append，扩容直接写新块，避免完整临时邻接副本和每条删除反复搬移。',[(S,'void BuildDeletionPlan'),(S,'void CompactSourceInPlace'),(S,'void RewriteSourceToNewBlock')],f'{plan} §D3；logs/d3_gate_20260729/。D2→D3 总 mutation 四图下降 23.0%/20.3%/14.0%/25.6%；最终 D3 五次中位相对 C1，WK/TW/FS 完整十批下降 5.7%/37.4%/31.5%。','D2 三次与 D3 五次并非同一交错 cohort；Orkut 对 C1 仍慢 11.5%，TW delete-only 子项回退，不能删掉负项。')
add('A04','当前拓扑与发布','固定生命周期线程池并行 source prepare/apply（I5–I9）','当前主路径','独立 source 的删除规划和 compact/rewrite 由固定 worker 池执行，默认 16-source grain 动态领取；allocation、epoch/edge count、retire 和 publication 保持必要串行，异常传回调用者。',[(S,'mutation_workers_->Run(phase_size'),('include/utils/fixed_worker_pool.h','class FixedWorkerPool'),(F,'CG_MUTATION_WORKERS')],f'{plan} §I8–I9；logs/i8_mutation_repeats_20260827T031043Z/。1→20 workers TW 完整十批中位 827.039→579.388 ms，FS 4734.041→3971.274 ms；mutation -73.9%/-79.3%。I9 topology residual 0.049%/0.067%。','这是同系统 CPU 资源消融，不是相对原版加速；Europe 完整时间 +0.52%，mutation 占比太小。reverse 另有自己的 worker 池，不能用这组比值声称 reverse 的扩展性。')
add('A05','当前拓扑与发布','24-byte 稀疏 descriptor patch 与兼容 16-byte GPU 描述符（C3/D1）','当前主路径','只发送实际 changed source 的 source/slab/offset/degree/version；scatter 写现有兼容 descriptor，删除曾额外常驻 GPU 的 24×V 字节 extended descriptor。CPU 验证有序唯一 source、版本与 epoch；检查模式直接比对邻接 digest。', [('include/groute/graphs/topology_contract.cuh','struct TopologyPatchRecord'),(G,'void ScatterTopologyPatch'),(G,'void PublishSparse')],f'{plan} §D1；logs/d1_gate_20260729/。OK/WK/TW/FS GPU 采样峰值减少 74/312/802/1506 MiB。','不能说完全没有 O(V) GPU 元数据：legacy descriptor/value/buffer/parent/epoch 等仍存在。patch 实际 payload 随 changed sources，预留容量则按最大 batch 预算，不严格等于当前 S。')
add('A06','当前拓扑与发布','预分配 publication 工作区与事件依赖发布（D2/I10）','当前主路径','load 阶段预留 pinned/device patch 和复用 events；生产 enqueue 一次非空 patch H2D、scatter、cache patch；consumer stream 等待 publication event，在已有同步点 Complete，完整 hash 只在检查模式执行。',[(G,'void ReserveSparsePublicationCapacity'),(G,'void WaitForSparsePublication'),(G,'SparsePublicationResult CompleteSparsePublication')],f'{plan} §D2、I10；logs/d2_gate_20260729/。D2 四图 publication 中位 0.397/0.427/0.089/0.297 ms，较 C4 完整 paper 下降 11.7%–17.5%。','不是整个 batch 无同步，也不是 CPU/GPU propagation overlap；D2 audit/production publication 不能当同工作量 kernel 对照。I10 pinned topology TW/FS 3.095/8.890 GiB，需报告 host 成本。')
add('A07','当前拓扑与发布','同一 mixed-batch 的稳定 source 分组与 phase 视图（I14/B5.4.1）','当前主路径','一次组织 delete/add 输入，按 source 稳定排序，平坦 destination 数组和 delete/add ranges 共用；phase-active source 索引让各 phase 只处理该 phase 的 source，避免遍历 union 并为无工作 source 分配结果。',[(U,'class GroupedUpdateBatch'),(U,'size_t PhaseSize'),(U,'size_t SourceIndex'),(F,'void PrepareGroupedUpdates')],f'{plan} §I14；iteration/subiteration_file/i17b541_fs1000k_test.md；tests/grouped_update_batch_test.cpp。I14 组合 TW/FS 每批 57.380/466.728→53.335/414.674 ms。','I14 收益是统一 effective+reverse 的组合证据，不能重复算作每个子机制的独立加速；phase-active 单项未证明稳定收益。当前仍保留 deletion-only 与 final 两个状态。')
add('A08','当前拓扑与发布','forward 权威有效变更供 reverse/publication 共享（I14）','当前主路径','只把成功匹配删除的负 count 和有效插入正 count 交给 reverse，缺失删除不产生虚假负债；publication 仅记录 changed source。reverse Prepare 排序、合并、预建槽位成功后，forward 才可见提交，reverse Commit 为 noexcept swap。',[(U,'struct EffectiveEdgeDelta'),(S,'metrics.effective_records = effective.size()'),(S,'observer.Prepare'),(R,'void Commit() noexcept')],f'{plan} §I14；logs/i14_effective_batch_20260906/；tests/dynamic_reverse_index_test.cpp。300 批随机/重复/缺失/删加/异常 oracle、ASan/UBSan 历史记录；两图开发下降 7.05%/11.15%。','不是最终态事务，不提前暴露 additions；forward/reverse 必须共同保持 deletion 中间态。无效 source/destination 的过滤边界应按实际接口记录，不能外推为通用输入清洗。')
add('A09','当前拓扑与发布','大批量共享 source plan 与 reverse 缓冲区所有权转移（I20）','显式 large；开发默认 regular','large 模式保留 PreparedResult 的单份重型规划，用 changed indices 供 apply/retire 等消费；effective vector 以 move 交给 reverse Prepare，删除重复 PreparedSource 数组和 reverse 输入副本。regular/large/auto 共用同一拓扑与 epoch。',[(S,'const bool shared_plan'),(R,'void Prepare(std::vector'),(U,'CG_BATCH_MAINTENANCE')],'iteration/subiteration_file/i20_shared_plan_20260915.md；logs/i20_reverse_20260915/combined_results.json。TW/FS10M 两批 regular→large 两次均值 12.185163→11.288533 s / 15.099269→13.650626 s，-7.36%/-9.59%；每轮消除 320 MB reverse 输入副本。','两次开发配对，不是正式显著性；取消的大图全阶段 gate 未补跑。auto 的 B≥1M 是初始统一入口阈值，不是已证明 crossover。布局字节不是 DRAM 总流量或 RSS 降低量。')
add('A10','当前拓扑与发布','mixed-source 稳定串行 radix 分组（B5/2026-09-14）','当前主路径，大列表自动使用','大列表用四个 8-bit source radix pass，保留同 source 的输入顺序及 delete-before-add；小于 4096 用稳定比较排序，scratch 与 batch updates 同阶。',[(U,'if (records.size() < 4096)'),(U,'for (unsigned shift'),('tests/grouped_update_batch_test.cpp','int main')],'iteration/subiteration_file/i17b7_b5_progress_20260914.md；logs/i17b7_b5_20260914/tw10000_radix/run.log。TW10M 两批 19030.224→17603.116 ms，grouping 3067.270→1724.086 ms；两批独立检查通过。','单次开发配对，7.50% 不是重复稳定结果；与后来默认关闭的并行 source radix 是两个不同改动，不能一概写成“radix 失败”。')
add('A11','当前拓扑与发布','两 phase changed-source 有序集合线性合并（I21-A/I24）','显式开关保留，默认关闭','delete/add 的 changed source 各自已排序，set_union+去重替代拼接后 sort+unique，scratch 跨批复用；复杂度由比较重排降为两个列表线性处理。', [('include/framework/publication_sources.h','void MergePublicationSources'),(F,'void FinalizePublicationSources'),('tests/publication_sources_test.cpp','int main')],'iteration/subiteration_file/i24_tw10m_publication_20260917.md；logs/i24_tw10m_publication_20260917/。TW10M ABBA 两批均值 11258.968→10685.928 ms，-5.0896%；排序 575.795→55.381 ms，解释约 90.8% 完整节省。','CG_MERGE_PUBLICATION_SOURCES=1。两次候选 10719.232/10652.624 ms 在历史原版 10715.850 ms 两侧；只是改善当前系统，不是已正式击败原版。')
add('B01','当前删除与插入计算','显式删除阶段正确性和 affected boundary 恢复（10.9/A/B1）','当前主路径','先在旧图失效 dependency，再物理删除并从删除后的权威 incoming 找替代距离，删除状态到 fixed point 后再处理插入；不再依赖插入全点启动补偿删除错误。',[(F,'void update_tree_del'),(F,'void RunGpuAffectedRepair'),(H,'[SSSP-DELETE-STAGE-CHECK]')],f'{plan} §10.8–10.9、A、B1。B1 对 CPU repair 的 WK/TW/FS mixed b5 完整时间下降 30.83%/34.92%/32.62%。','这些是相对历史 CPU repair 内部版本；不是相对原版的公平最终结果。删除检查并非每次生产性能运行都开启。')
add('B02','当前删除与插入计算','事件驱动 compact affected queue 与增量失效区间（B2）','当前主路径','删除种子和失效后继直接进入 compact queue，消费 [frontier_begin,frontier_end) 新区间；原子 parent 失效/标记抑制重复，并在完整失效后重置 affected values。取消 repair 的全图 state gather 与固定全 segment 重建。',[(D,'void reset_del_edges'),(P,'bool AtomicInvalidateParent'),(F,'uint32_t frontier_begin = 0'),(D,'void reset_affected_values')],f'{plan} §B2；tests/exact_source_executor_test.cu 及六图历史检查。相对 B1，WK/TW/FS delete -68.84%/-88.87%/-71.67%，完整 -34.37%/-35.63%/-21.26%。','当前 update_tree_del 仍每批 cudaMemset 全 V reset 数组；不能把整条删除路径声称为完全无 O(V) 初始化。完整传播是局部化，非所有管理成本均局部化。')
add('B03','当前删除与插入计算','非 tight stored-parent 的删除依赖防护与字节原子标记','当前正确性修复','距离/parent 分离更新会有 stored-parent 不 tight 的窗口；删除/失效传播同时检查被删/失效 tight edge 与 parent tightness，避免只信存储 parent 而漏失效；对 byte reset 使用 CAS word 更新。',[(P,'const bool parent_tight'),(P,'const bool invalid_dependency'),(D,'void reset_del_edges'),(P,'atomicCAS(bits')],f'{plan} §I0–I2；iteration/subiteration_file/system_review_20260912.md §3.4；samples/hybrid_sssp/hybrid_sssp.cu 的 Bellman 与 witness 检查。','这是漏修复防护，不代表全部 parent 数组合法；历史 TW/FS 检查仍有 stored-parent invalid witness。论文外部结果应承诺 distance/existential tight witness，不能自动承诺完整最短路径树。')
add('B04','当前删除与插入计算','不可变 sorted incoming base + 有符号 occurrence overlay（E4-R2/I14）','当前主路径','CPU reverse base 按 destination/source 排序，动态部分按 source count 归约；materialize 以双指针合并 base 重数与 overlay，只输出仍存在的 dependency source，避免每个 affected destination 临时 unordered_map。',[(R,'void Build'),(R,'void MergeIncoming'),(R,'struct Delta')],f'{plan} §E4-R2；tests/dynamic_reverse_index_test.cpp。FS 单批 prepare/H2D/closure 7.097/0.258/4.299 ms，完整 11.654 ms；十批平均 24.75 ms，二者不可混写。','CPU 仍有全图 base incoming，不能说“不保存 CSC”；省的是常驻 GPU 全 CSC/每边版本 metadata。overlay 跨批持久增长，目前没有已验证在线 base compaction。')
add('B05','当前删除与插入计算','affected-only incoming 物化与紧凑 H2D（B2/R2）','当前主路径','只为 compact affected destination 组织 offsets/sources，在 GPU 运行 affected pull 至无变化；incoming 工作区按需求扩容并保留，拒绝把整个图 state 传回 CPU 做 repair。',[(R,'MaterializeMetrics MaterializeIncoming'),(F,'void EnsureGpuAffectedRepairCapacity'),(F,'void RunGpuAffectedRepair')],f'{plan} §B2、R2；I17/I19 incoming 和 h2d_bytes 计数；tests/i17b5_pull_smoke.py。','传输规模为 affected incoming，不仅是 affected 顶点数；保留容量可能大于当前 A/E_A。不是零拷贝方案，且初始化 base 排序成本必须单列。')
add('B06','当前删除与插入计算','destination 批量槽位预建与并行 overlay merge（B5.3）','当前主路径','排序后生成 destination ranges，先完成 map 槽位创建/扩容，再并行只读旧向量、构造独立替代向量；commit 无分配 swap，避免并行修改同一共享 map。',[(R,'auto prepare_shard'),(R,'auto merge ='),(R,'merge_workers_->Run(pending_')],'iteration/subiteration_file/i17b53_batch_reverse_screen.md。FS1M 两批均值 3931.120→3705.730 ms（-5.73%），reverse -13.26%；方向一致但样本 spread 约6.6%–6.8%。','独立 reverse worker 池，不是复用 source mutation 实例；早期短测不足以宣布整个 B5 已正式封板。')
add('B07','当前删除与插入计算','reverse destination-range 分片与 grain=1 预建（B5.4.3）','显式 64 shards，默认 1','floor(dst*shards/V) 给每个 worker 独占一个 map 和连续 pending 范围，独立 reserve/insert 后统一并行 merge；降低单 map 查询/重哈希串行税，不增加 GPU 图副本。',[(R,'size_t ShardIndex'),(R,'merge_workers_->Run(deltas_.size(), prepare_shard, 1)'),(F,'CG_REVERSE_SHARDS'),('include/utils/fixed_worker_pool.h','size_t grain = 16')],'iteration/subiteration_file/i17b543_reverse_shards.md；logs/i17b5_20260911/b543_reverse_profile/。FS1M 同 binary 十批 26173.694→15173.065 ms（-42.0%），reverse -86.1%，RSS +46.96 MiB。','一次十批对照；小批可能固定开销回退。不能把64写成生产默认，也不能说扩容/history debt 已消失。原几何扩容替代分支已撤回。')
add('B08','当前删除与插入计算','effective delta radix 与 source 已有顺序复用（B5）','当前主路径','大记录列表稳定 radix 排 destination/source；先检查 source 单调，forward 已有 source 序则只做 destination 四遍，否则八遍；小列表比较排序，不信任外部调用者口头保证。', [('include/framework/effective_delta_sort.h','inline void SortEffectiveDeltas'),(R,'topology::SortEffectiveDeltas')],'iteration/subiteration_file/i17b5_incoming_source_order_20260914.md；tests/dynamic_reverse_index_test.cpp。与并行 incoming、warp pull 的组合 TW1M/TW10M/FS10M 完整下降 53.52%/29.80%/15.42%。','上述三项组合，不能给 source-order 单项分配全部收益；后来 I25 并行 reverse radix 默认关闭，不影响此串行机制保留。')
add('B09','当前删除与插入计算','4096-destination tile 并行 incoming 物化（B5）','当前主路径','worker 各自一次扫描 base/delta 到局部向量，prefix 后并行拷贝至连续 CSR，保持 destination 输入顺序和行内 source 有序唯一；复用 reverse 池。',[(R,'constexpr size_t tile_size = 4096'),(R,'std::vector<Tile> scratch')],'iteration/subiteration_file/i17b5_incoming_source_order_20260914.md。组合测试 TW10M incoming 2489.954→246.753 ms、FS10M 1902.253→283.643 ms（两批）。','新增 host scratch 和输出一次 CPU copy E×4 B；不是 zero-copy，也不能从进程 RSS 略降推断 scratch 不存在。4096 是粒度而非按图选择。')
add('B10','当前删除与插入计算','warp 协作 incoming min-plus 归约（B5）','当前主路径','一 warp 扫一 affected incoming row，按(distance,parent ID) shuffle 归约，lane0 提交状态和 changed queue；避免单线程串行长行。非32倍 block 退为 width=1。',[(F,'__global__ void GpuAffectedPullRelax'),('tests/i17b5_pull_smoke.py','')],'iteration/subiteration_file/i17b5_incoming_source_order_20260914.md。组合 TW1M closure 2008.007→110.780 ms，TW10M 2888.629→438.964 ms；TW/FS10M 全阶段检查通过。','与 host 两项共同配对；不声称全部收益可独立归于 warp，也不声称传播轮数一定下降。parent 局部 tie 处理不是全局 parent 修复。')
add('B11','当前删除与插入计算','added-edge seed 代替全点 kickoff（10.8–10.9/B3/R1）','当前主路径','只松弛本 phase added edges，成功改善 destination 才激活，形成精确 source 种子；删除 repair 提供可靠的前置 fixed point，避免插入全点扫描掩盖删除漏洞。',[(F,'__global__ void SeedAddedEdgeFrontier'),(F,'void BeginInsertionEpoch'),(F,'SeedAddedEdgeFrontier<TValue><<<')],f'{plan} §10.7–10.9、E4-R1；tests/exact_source_frontier_test.cpp。早期全点 kickoff 占 WK/TW/FS add-compute 24.83%/38.43%/88.18%（机会画像）。','这些百分比不是当前收益；direct seed 初版失败被修复，不能把失败版本列为正确优化。只有有实际改善的 source 扩边，仍允许后续必要再激活。')
add('B12','当前删除与插入计算','精确 source 的 GPU cooperative closure 与 wave ticket 去重（E4-R1）','当前主路径','compact input/output queue、block/source 直接访问连续邻接；cooperative grid.sync 在 GPU 内交换队列并判断空，successful relax 用(epoch,wave) ticket 去重，每轮无需 host frontier 往返，最终一次收敛同步。',[(F,'__global__ void RunExactGpuClosure'),(F,'void RunExactSourceClosure'),('include/framework/exact_source_frontier.h','class ExactSourceFrontier'),('tests/exact_source_executor_test.cu','int main')],f'{plan} §E4-R1；日志 seed_partition_rebuilds=0、host_frontier_syncs=0。历史十批 closure WK/TW/FS 5.598/2.545/7.877 ms。','独立 ExactSourceFrontier 是协议/测试基座，生产 GPU 使用 ticket，不应写成 host 类直接驱动每波。16-bit wave、cooperative residency 和32-bit距离有边界；非 ordered 历史路径存在返回后 overflow 检查。')
add('B13','当前删除与插入计算','GPU 有序删除：affected local CSR + 稀疏 bucket frontier（I17-A/B6/I18）','显式大直径模式','从 incoming 识别 affected 内部边并转置为 local outgoing CSR，boundary incoming 初始化局部距离；按 distance/128 的最小 bucket 扩展，pending 去重且保留 deferred，最终 publish values 并重建 affected tight parents。',[(O,'Metrics Run'),(O,'__global__ void Seed'),(O,'__global__ void FindActiveBucket'),(O,'__global__ void Parents'),(F,'if (ordered)')],'iteration/subiteration_file/i17b6_completed_analysis.md；logs/i17_scaling_20260911/experiments/results.json。USA/EU100K 两批 pull→ordered 80.405→16.492 s / 233.636→36.374 s；1M 为 186.018→76.336 / 571.462→221.641 s。','当前 Run 分配 local(nodes,UINT32_MAX)，有 O(V) host 初始化，不能称全部准备 O(A)。权重1..128，非完整任意权 delta-stepping；这些是旧删除-only ordered 配对，当前总开关语义后来改变。')
add('B14','当前删除与插入计算','有序删除的设备控制合并与双队列首尾复用（I17-B）','当前 ordered 路径','bucket/selected count 留在设备，Reset/Find/Partition/Expand 同 stream；selected 从 scratch 前部写、deferred 从尾部写，Expand 先保留 deferred 前缀后 append，新一轮只读一次 counters，省第三条 A 队列。',[(O,'__global__ void ResetControl'),(O,'__global__ void PartitionActive'),(O,'if(deferred) for'),('src/i17a_delta_replay.cu','int main')],'iteration/subiteration_file/i17b_gpu_cost_results.md。独立 replay complete service EU/USA 7960.971→7037.937 / 3750.465→3445.975 ms，-11.6%/-8.1%；GPU -79.1/-47.5 MiB；55 回归、6 memcheck 历史通过。','replay service 不含生产 authoritative handoff，不能直接当完整 batch 加速；独立队列复用只证明空间节省，控制合并是主要成本证据。')
add('B15','当前删除与插入计算','GPU 插入距离窗口：carry 与改善事件统一去重（I22）','显式大直径模式；普通默认 block','在现有 cooperative closure 上求 pending buffer 最小值，仅处理[min,min+127]，远任务不提前 commit value，carry 与新改善用同 ticket，下一波读最新 buffer，抑制跨波反复远距离扩边。',[(F,'if (Ordered) metrics[4]'),(F,'const bool deferred = Ordered'),('tests/i22_ordered_insertion_test.py','def ')],'iteration/subiteration_file/i22_ordered_insertion_20260916.md；logs/i22_ordered_20260916/summary.json。EU1M 两批完整 195.076038→42.245784 s（4.62×），插入172.925756→20.326482 s，edges 25,366,217,005→108,131,195。','单轮两批；waves反而7334/7324→22293/22455，收益是减少边重复松弛，不是减少轮数。FS/TW八组插入全回退；窗口扫描/carry仍大，不是物理桶数据结构。')
add('B16','当前删除与插入计算','大直径传播模式与 batch 维护模式独立接线（I22）','当前配置行为','CG_ORDERED_REPAIR=1 同时强制有序删除和有序插入，优先于遗留 CG_INSERTION_SCHEDULE；普通模式才读取 block/thread/ordered，默认 block；CG_BATCH_MAINTENANCE 独立。',[(F,'const bool large_diameter'),(F,'const std::string schedule ='),(U,'const std::string mode')],'iteration/subiteration_file/i22_ordered_insertion_20260916.md 最终模式优先级；logs/i22_mode_priority_20260916/result.json。EU/USA10K/100K范围筛查完整下降24.17%–45.68%，仅开发证据。','是模式整合而非新的第3种算法；旧消融脚本用新 binary 时 ordered=1 会使 block 请求也执行 ordered，必须冻结旧 binary 或修改消融方式。')
add('C01','缓存、正确性与工程修复','producer-native touched cache 邻接 patch（F1-C0/P0）','当前主路径','稀疏 topology publication 时同步更新 touched resident 的 cache payload；degree 不增长复用原槽，增长时在相同 cache 分配的尾部为该 source 预留新连续位置，溢出则失效并从权威 cold 邻接读取。',[(G,'bool ReserveCachePatchOrInvalidate'),(G,'void PatchOrInvalidateCachedAdjacency'),('tests/cache_tail_fallback_test.cu','int main')],f'{plan} §F1-C0/P0；logs/f0l_critical_path* 与相关 cache trace。TW 单次十批 cache链1096.049→42.656 ms，完整1618.501→594.654 ms；增长/尾部回退有定向测试。','原有 hot cache 不是本次发明；贡献是局部拓扑更新不必触发全 cache 重建。上述完整-63.3%是单次screening，非正式重复；tail allocator仍有容量边界。')
add('C02','缓存、正确性与工程修复','精确 desired membership refresh gate 与安全 full-refresh fallback','当前主路径','候选仍按完整 hotness 顺序生成；检查 desired resident 是否全部有效以及数量是否匹配，满足则跳过 eviction/compact/load；首次/缺失/数量变化才刷新，判定与 eviction delta 标记分离。', [('include/framework/cache_refresh_gate.h','class RefreshGate'),(F,'index_t CacheCandidateCount'),(F,'const index_t admitted = CacheCandidateCount'),('tests/cache_refresh_gate_test.cpp','int main')],f'{plan} §F1-C0/P0、I4-R3；tests/cache_patch_trace_test.cpp、tests/cache_tail_fallback_test.cu。TW历史10批10次skip且correctness通过。','没有删除全顶点hotness和candidate排序。此gate与已撤回resident delta extent allocator不同；不能因有fallback就声称所有图都保持局部refresh。')
add('C03','缓存、正确性与工程修复','SSSP hotness score/ID 配对纠错与确定性 tie 顺序（I15）','当前正确性修复','按 node 写score时同时重置当前ID buffer为identity，稳定降序CUB排序得到(score desc, ID asc)；避免前批ID排列与新score错配。',[(D,'void comp_hotness_sssp'),(F,'kernel::comp_hotness_sssp'),('tests/hotness_pairing_test.cu','int main')],'iteration/subiteration_file/i15_event_contract.md；logs/i15_pairing_fix_20260907/validation/。旧TW/FS首批 mismatch 19,485,389/46,931,414；纠错后22个audit样本为0，均值52.0702/346.0386 ms/批是新基线。','语义纠错而非事件维护算法收益；PR独立kernel未被此项验证。四个byte窗口仍模256计数，分数0..1020。')
add('C04','缓存、正确性与工程修复','CUB sort/scan 工作区分离、按需分配与释放','当前工程修复','sort和scan分开临时buffer，scan只在首次需要时分配，之后复用，析构释放，补CUB错误检查；消除每批scan重复分配/覆盖sort指针的问题。', [('include/framework/graph_datum.cuh','size_t sort_temp_storage_bytes'),('include/framework/graph_datum.cuh','~GraphDatum()'),('include/framework/graph_datum.cuh','void ensure_candidate_vertex')],'git diff f527ba4 -- include/framework/graph_datum.cuh；与原版HEAD相比也属于新增；相关cache回归和构建记录。','未找到该项独立完整性能消融，不能给独立加速数；应列为资源生命周期/健壮性工程工作，不能遗漏但不单独包装论文算法创新。')
add('C05','缓存、正确性与工程修复','segment 队列边界、空分段容量和 reset 初始化修正','当前工程修复','队列表从512扩为512+2以容纳两个combined worklist；校验SEGMENT∈[1,512]，空段queue至少1，node_reset分配后清零；历史type[1]按两个int注册的问题改为type[2]，避免host注册越界。', [('include/framework/graph_datum.cuh','kCombinedWorklists'),('include/framework/graph_datum.cuh','SEGMENT must be'),('include/framework/graph_datum.cuh','queue_capacity'),('include/framework/graph_datum.cuh','cudaMemset(m_node_reset_datum'),(F,'int type[2]')],'git diff f527ba4 -- include/framework/graph_datum.cuh；I13/后续小图构建检查。','修正越界/未初始化风险，非独立优化收益；当前小图SEGMENT512有序路径仍有已记录配置错误，不能称所有配置问题已解决。')
add('C06','缓存、正确性与工程修复','Bellman、存在性 tight witness、stored-parent 诊断与逐阶段checksum','当前验证基础','在authoritative ChunkStore上检查source距离、无可松弛边、finite顶点存在tight入边，独立输出stored-parent edge/distance失配；delete-stage、batch、final三层检查并把失败传出进程。',[(H,'static BellmanRelaxCheckResult CheckBellmanRelaxed'),(H,'[SSSP-DELETE-STAGE-CHECK]'),(H,'[SSSP-BATCH-CHECK]'),(H,'[SSSP-FINAL-CHECK]')],f'{plan} §A、I0–I3、I13；logs/i2_six_graph_correctness_20260825/。六图各10次删除/批末及final检查历史通过。','历史二进制的六图通过不能自动证明当前所有新增模式通过；distance hash是校验指纹，不代替oracle，也不要求parent checksum相同。')
add('C07','缓存、正确性与工程修复','ordered hash/multiset拓扑 replay 与CPU/GPU发布一致性审计','当前验证基础','独立重放 occurrence 更新，对touched source比较顺序hash、多重集合hash、degree、edge count；GPU从实际patch和mapped slab计算digest与CPU权威邻接核对。', [('include/framework/topology_replay.h','class TopologyReplayModel'),(F,'[TOPOLOGY-AUDIT]'),(G,'void HashPublishedAdjacency'),('src/topology_replay.cpp','int main')],f'{plan} §C1、D1–D3、I9–I10；tests/topology_contract_test.cpp。I9 structural_mismatches=0；I10 TW/FS 10次publication mismatch/stale reject均0。','审计是check/diagnostic能力，不计为算法提速；digest碰撞理论存在，不替代定向精确邻接oracle。')
add('C08','缓存、正确性与工程修复','构建、跨应用兼容与 Release 测试断言修复','当前工程工作','BFS/CC/PR保留框架编译兼容flag；测试目标显式保留assert，避免Release把断言中的实际操作删去；Loader补显式include及::Record消歧；共享CUDA控制入口接通信scope；删除旧应用AccumulateBuffer_del虚接口，改用共用失效逻辑；I22修正cooperative launch的引用/按值ABI类型不一致，让occupancy和launch使用同一实际kernel实例。', [('tests/source_local_chunk_store_test.cpp','#undef NDEBUG'),('include/framework/Loader.h','typedef ::Record'),('samples/hybrid_bfs/hybrid_bfs.cu','sssp_cpu_partition_capacity'),('samples/hybrid_cc/hybrid_cc.cu','sssp_cpu_partition_capacity'),('samples/hybrid_pr/hybrid_pr.cu','sssp_cpu_partition_capacity'),('include/framework/variants/api.cuh','kSupportsGpuDeletionRepair'),(F,'using Graph = decltype(graph)')],f'{plan} §I13–I15；全量四应用构建记录及CMake测试清单。','编译兼容≠BFS/CC/PR都实现并验证相同优化。论文算法实证主线仍SSSP；新增header/计量标记不是每个都算新算法。')
# Historical studies: use exact historical symbols or archive entries, never invented current locations.
add('C09','缓存、正确性与工程修复','初始化按真实活跃状态自然收敛，取消1000轮伪终止（P1）','当前主路径正确性修复','Start初始化只在全部segment活跃计数为零后退出，允许道路图长传播；不再把固定1000轮当作收敛。',[(F,'void Start(index_t priority_detal'),(F,'while (!convergence)')],f'{plan} §P1；logs/p1_europe_natural_init_20260824T133914Z/。Europe约11742轮自然收敛并通过初始Bellman。','这是正确性工作，不是缩短初始化耗时。历史同cohort十批gate仍失败：batch0删除后missing_tight_witnesses=1，最终247；不能把初始化通过扩展为当时整个P1完成。旧LOG的1000诊断字符串仍在其它位置，不代表Start仍硬退出。')
add('C10','缓存、正确性与工程修复','Loader批次表和边数组有效长度修复','当前可靠性修复','原版对仅reserve的batch vector按下标写入，边数组亦只有reserve；改为batch push_back和按总边数resize，再写入具体元素，初始化成员并补类型/头文件兼容。',[('include/framework/Loader.h','m_batch_size.push_back'),('include/framework/Loader.h','added_edges_w.resize'),('tests/i19_loader_test.cpp','int main')],'对照原仓库7ffcb29:include/framework/Loader.h；tests/i19_loader_test.cpp与tests/i19_gpu_smoke.py；部分修复在本仓库初始提交已有。','属于输入可靠性和工程工作，不是算法性能创新；不据此声称所有格式错误输入都有完整验证，流式合法性检查另见T01/T03。')
add('N01','历史原型、消融及负结果','初始协同框架：segment/CPU_HOME、稀疏状态snapshot、proposal reduce/merge','历史实现，当前已被替代','首提交已含CPU候选选择、owner/shadow标记、CPU读host邻接、按destination压缩proposal、GPU atomic merge与source commit；这是相对原版的新增工作，不能因已在init中就漏统计。', [('git:f527ba4:include/framework/framework.cuh','MergeCpuRelaxProposals'),('git:f527ba4:include/framework/framework.cuh','MergeCpuSourceCommits'),('git:f527ba4:include/framework/framework.cuh','CoopExecMode')],'f527ba4 与原版7ffcb29内容比对：framework原版2188行、init4572行；docs/cggraph_cpu_gpu_integration_plan.md。','最初提交不是原始基线；初始内部功能实际存在，但无法由该提交确定此前每步开发日期/工时。不是当前推荐执行路径。')
add('N02','历史原型、消融及负结果','CPU read-only overlap probe、dry-run与production merge分步验证','历史实现，已替代','先测CPU读PMA与GPU窗口重叠，再加入真实state snapshot、proposal生成/压缩、诊断或生产GPU merge；剥离诊断probe与真实compute，量化hidden/exposed CPU service。', [('git:e6bc406:include/framework/framework.cuh','RunCpuOverlapProbeDryRun'),('git:e6bc406:include/framework/framework.cuh','ExecutePolicy_Converge_PacketDryRun'),('git:e6bc406:include/framework/framework.cuh','ExecutePolicy_Converge_PacketProductionMerge')],'e6bc406（2026-06-20，Overlap）；git增加上述函数及SSSP/BFS/CC flag；主计划packet v1。','read-only probe本身不改变device结果，不能记为CPU真正替代GPU计算；独立性能收益未从本次审计中确定。')
add('N03','历史原型、消融及负结果','CPU-owned source packet、GPU互斥skip与重叠merge','历史机制成立，性能路线冻结','CPU完整覆盖所选active source并提交source状态，GPU按epoch owner跳过同source；CPU线程generate/compress与GPU delta重叠，barrier后merge；skip audit检验重复/漏扫。', [('git:e6bc406:include/framework/framework.cuh','ExecutePolicy_Converge_PacketOverlapMerge'),('git:9b590a2:include/framework/framework.cuh','ExecutePolicy_Converge_PacketSkipAudit'),('git:0e036c8:include/framework/framework.cuh','EmitCoopOwnedSummary')],f'{plan} §10.1–10.6；9b590a2、0e036c8、caf1fc2。COOP-OWNED-SUMMARY覆盖实际CPU边、GPU skip、通信和隐藏时间。','后来B3删除packet生产dispatcher与兼容flag；不能把当前默认当packet协同，日志统计框架是研发工作而不是端到端胜出。')
add('N04','历史原型、消融及负结果','source policy、CPU full-dst prefilter与success-only dirty维护','历史消融，部分负结果','比较active_frontier/degree/cache/history等选择；CPU预查目的状态减少无效proposal；GPU仅成功merge的destination进入dirty queue；缓存active counts并仅重建dirty segments。', [('git:9b590a2:include/framework/framework.cuh','PostComputationBWDirtySegments'),('git:9b590a2:include/framework/framework.cuh','RefreshSegmentActiveCountsFromQueues'),('git:caf1fc2:include/framework/framework.cuh','SelectCpuPacketSources')],f'{plan} §10.1–10.6、§8。FS prefilter proposal20238→100，H2D251988→8880 B，PostBW63.238→12.013 ms，但总18846.262→19240.104 ms；source排序未稳定获益。','success-only dirty是有用机制验证，但不能把prefilter通信下降宣称端到端加速；初始active-partition优化被后来的exact-source路径吸收/替代。')
add('N05','历史原型、消融及负结果','统一活跃partition dispatcher与fixed destination owner（10.8/B3）','历史substrate，非默认owner','off/hybrid共用收敛入口，跳过inactive segments；owner固定于epoch，seed/reduce/commit/activate遵循唯一destination owner，双向min-reduced slab；Stage/HostClosure/Commit拆分支持真实重叠。',[(F,'void ExecutePolicy_Converge'),(F,'void StageGpuToCpuBoundary'),(F,'void RunCpuOwnedClosureHost'),(F,'void CommitCpuOwnedClosure')],f'{plan} §10.8、B3；Wiki/TW/FS capacity0/2距离checksum相同，overlap最大0.308/0.007/0.059 ms。','owner CPU useful service太小，无可靠非零capacity赢家；当前仍存在历史函数和可选flag，不能写成所有CPU owner代码已物理删除。')
add('N06','历史原型、消融及负结果','拓扑分区、双层domain/region与冻结METIS map（E0/E1）','历史研究与离线工具','分别尝试quotient、RCM、固定label propagation、80-region/双域；最终固定seed/1.05 imbalance/edge-cut的METIS，按out-degree权重做静态domain，trace仅事后验实际boundary/local depth。', [('scripts/topology_cpu_quota.py','def '),(F,'sssp_cpu_domain_map')],f'{plan} §E1；logs/e1b_metis_cross_graph_20260731_143415/。WK/FS successful boundary/internal0.448/0.569，TW1.129；FS一次离线2425s、RSS约74GB。','分区器本身为第三方METIS，不宣称原创；map通过结构gate不等于CPU执行性能收益。需列初始化/持久map校验成本。')
add('N07','历史原型、消融及负结果','source-state co-ownership、持久CPU状态、dirty scatter与双域删除闭包（E2）','历史路径仍有代码，非推荐生产','value/buffer/parent和source遍历归同owner；CPU本地多层closure，跨域只送boundary；初始一次handoff、跨批持久state，删除后稀疏状态事件而非每批全域gather，dirty scatter取代全域回写。',[(F,'void RunCpuOwnedClosureHost'),(F,'CpuAffectedClosureStats RunCpuOwnedAffectedPullClosure'),(F,'void ScatterCpuRepairEvents')],f'{plan} §E2/E2-C。WK首轮869 vertices/21838 edges/7层closure；4.1M CPU顶点首轮全scatter改为864点10368B；两批reconcile1521/1806点。','机制/正确性成立，但TW/FS单次domain仍慢，不能将少拷贝包装为最终性能主贡献。CPU路网PQ删除与此历史owner分支是不同代码。')
add('N08','历史原型、消融及负结果','changed-source版本事件、SPSC通道、credit与稳定空观测终止（E3）','协议实现保留，owner主线性能否决','仅发送真正changed且跨域依赖source，epoch/version/kind区分invalidation/replacement；两条有界SPSC ring在发布前reserve credit，队列满回滚，双域work/event/channel连续两次稳定为空才终止。', [('include/framework/dual_domain_event_runtime.h','class SpscEventChannel'),('include/framework/dual_domain_event_runtime.h','class SourceVersionGate'),('include/framework/dual_domain_event_runtime.h','class DualDomainEventRuntime'),(F,'uint64_t GatherGpuRepairBoundaryEvents')],f'{plan} §E3；tests/dual_domain_event_runtime_test.cpp。双线程各50000事件、历史100次压力无泄漏；最终E3 TW/FS相对all-GPU仍慢5.8%/16.0%。','每轮join的E3-B1已撤回；最终是SPSC不是计划里的MPSC，不能把两种写混。协议正确性不等于最终应用速度获益。')
add('N09','历史原型、消融及负结果','持久双向dependency record与mapped linked incoming（E4-A1/A2）','协议类保留；linked生产原型撤回','同一versioned dependency record服务incoming与跨域source依赖，epoch retire/reclaim；实验以16-byte/source-next-born-retired链表让GPU直接mapped遍历，消除repair edge H2D。', [('include/framework/persistent_dependency_graph.h','class PersistentDependencyGraph'),('tests/persistent_dependency_graph_test.cpp','int main')],f'{plan} §E4-A1/A2；logs/e4a2_cross_graph_20260811_152451/。FS closure26.280→90.818ms，repair wall81.926→98.716ms，load230s、RSS约78GB，否决。','当前协议模型不等于当时mapped linked生产实现；生产删除部分仅由历史日志/归档说明，不能冒充当前可调用代码。')
add('N10','历史原型、消融及负结果','destination-local连续dependency chunk及两阶段容量事务（E4-A2）','独立store/测试保留，生产接线撤回','用连续mapped incoming+warp读取替代链表；PrepareBatch统一预检最终容量，ApplyPreparedDeletions→repair→ApplyPreparedAdditions→Publish，保留occurrence与中间态。', [('include/framework/destination_local_dependency_store.h','class DestinationLocalDependencyStore'),('tests/destination_local_dependency_store_test.cpp','int main'),('tests/dependency_warp_mapping_test.cu','int main')],f'{plan} §E4-A2连续chunk。FS closure44.959ms改善，但dependency维护127.696ms，paper859.891对780.234ms回退约10.2%；容量投影工具scripts/analyze_e4a2_capacity.cpp。','当前forward SourceLocalChunkStore与这个被否决的reverse store不是同一结构；不能因reverse变体失败否定forward主线，也不能把保留测试当生产启用。')
add('N11','历史原型、消融及负结果','显式服务/通信/placement/迁移成本owner planner与synthetic calibration（E4-R3）','独立模型/工具，未形成获胜在线选择器','memory eligibility为硬约束，成本max(cpu,gpu)+event+dependency+topology+placement+migration；synthetic CPU/GPU/event标定，all-GPU/full部署候选与edge-cut/placement消融分开。', [('include/framework/owner_cost_planner.h','class OwnerCostPlanner'),('tests/owner_planner_calibration.cu','int main'),('scripts/evaluate_e4r3_shadow.py','def ')],f'{plan} §R3；logs/e4r3b_shadow_20260813/。WK/TW/FS模型all-GPU/full0.503/0.857、0.056/0.097、0.674/1.834ms均选all-GPU。','shadow prediction不是实测。R3-C旧domain dispatcher SIGABRT不是“full实测较慢”；未完成同exact-source的CPU/full运行时比较。')
add('N12','历史原型、消融及负结果','affected SCC/sub-DAG、sink语义、临界路径与真实crossover replay（F）','离线研究与负结果','trace构建weak components/SCC condensation，区分独立可并行component、CPU前缀后继依赖和需要迭代事件的suffix；sink保留incoming reduce/commit但不计传播出边，CPU/GPU replay按真实先后关系记成本。', [('include/framework/affected_component_trace.h','struct '),('src/affected_component_analyzer.cpp','struct SubDagCandidate'),('src/affected_component_analyzer.cpp','struct CriticalPath'),('src/f1_crossover_replay.cu','int main'),('include/framework/f1_replay_state.h','struct ')],f'{plan} §F1-C；iteration/subiteration_file/fable5结论.md。偏CPU下界中TW仍慢22.4%、FS95.6%，R-MAT只作crossover边界。','F2–F4未实施；不能把这些数扩写成所有图/所有CPU算法数学上不可能。真实代码和artifact构成大量研究工作，适合负结果/动机附录。')
add('N13','历史原型、消融及负结果','完整hotness事件契约、expiry/mask/degree/wrap模型（I4/I15）','独立模型；生产仍全扫描','证明topology touched不是hotness完备集合；事件必须覆盖实际counter writer、四窗口expiry、reachability mask、degree变化和初始化；保留uint8回绕、零分ID顺序、严格容量prefix。', [('tests/hotness_event_model_test.cpp','int main'),('include/framework/hotness_candidate_trace.h','struct '),(F,'index_t CacheCandidateCount')],'iteration/subiteration_file/i15_event_contract.md；2560随机snapshot模型与mask/wrap/expiry/zero-degree等fixture。','当前精确GPU closure并不在所有距离更新处增加hotness，不能用“成功relax集”代替真实counter事件；GPU完备writer事件捕获没有生产化。')
add('N14','历史原型、消融及负结果','有限分数域 weighted treap candidate index与trace replay（I15）','独立原型保留，性能否决','1021个score组，每组按ID的intrusive treap，subtree degree/count支持严格prefix容量选择，包含零分大集合；捕获生产排序结果与独立hash做回放oracle。', [('include/framework/weighted_score_index.h','class WeightedScoreIndex'),('src/hotness_candidate_replay.cpp','int main'),('tests/weighted_score_index_test.cpp','int main')],'iteration/subiteration_file/i15_event_contract.md；logs/i15_candidate_index_20260907/。十批index更新+查询TW11200.956/FS27544.501ms，预算180.304/467.7815ms，约62.1/58.9倍。','完整事件采集/通信/输出成本还未计入；此乐观下界已经失败，生产capture入口移除。不是所有有限域算法都被否定，不能写已部署增量candidate。')
add('N15','历史原型、消融及负结果','resident-set delta与单/双extent cache allocator（I4-R）','生产原型已撤回','desired/resident delta分类，尝试GPU命令发布和host extent规划，随后两段分配/回收shrink slack；审计区分membership churn与topology invalidation。', [('archive:logs/i4r1_audit_20260826/',''),('archive:logs/i4r2_two_extent_20260826/',''),('src/cache_patch_replay.cpp','int main')],f'{plan} §I4-R1–R3。TW/FS原型1021.654/6416.829ms慢于I3 646.987/4210.008ms；FS后批plan750.697/850.514ms仍因碎片fallback。','当前只保留trace/replay与touched patch/gate，原extent生产代码位置需历史归档，不能给当前LoadCache函数当作已删除allocator实现。无独立源码归档时明确仅日志证据。')
add('N16','历史原型、消融及负结果','最终态repair模型与source COW事务/overlap（I11/I12）','语义模型保留；生产事务已删除','按最终multigraph parent arc重数判断依赖是否真断，CPU准备touched next chunks与GPU old-epoch invalidation重叠，单次commit/publication、boundary+added seeds统一closure；20,000随机Dijkstra模型验证。', [('tests/final_state_repair_model_test.cpp','int main'),('archive:logs/i13_cleanup_20260906/pre_cleanup.tar.gz','include/groute/graphs/source_local_chunk_store.h'),('archive:logs/i13_cleanup_20260906/pre_cleanup.tar.gz','include/framework/framework.cuh'),('paper/work_audit_20260917/historical/i12_pre_cleanup/include/groute/graphs/source_local_chunk_store.h','void PrepareTransaction'),('paper/work_audit_20260917/historical/i12_pre_cleanup/include/groute/graphs/source_local_chunk_store.h','ChunkStoreBatchMetrics CommitPreparedTransaction')],'iteration/subiteration_file/i11_final_state_repair_semantics.md、i12_i10_baseline_manifest.md；主计划I12。TW两批约快11.6%，FS回退约5%；publication降至约1.9ms仍被COW/cache抵消。','I13删掉PrepareTransaction/CommitPreparedTransaction生产API并恢复两阶段；不能把本机制写为当前已启用性能贡献。多版本额外空间和初始化/准备成本不可隐藏。')
add('N17','历史原型、消融及负结果','事务失败后的运行时收敛与回归封板（I13）','已完成清理','清理I12专属next-state/final-boundary/transaction dispatcher，保留并行mutation/epoch；reverse缺失删除不抵消未来插入，恢复删除检查，减少冗余状态空间。',[(F,'void update_tree_del'),(S,'ChunkStoreBatchMetrics ApplyMutationPhase'),('scripts/run_i13_smoke.sh','')],'logs/i13_cleanup_20260906/README.md；主计划I13。核心净删698行，22/22CTest、四应用构建、TW/FS十批距离checksum与I10一致。','净删行数是当时清理范围，不是当前全仓净增量；清理没有将仍被调用的所有历史owner分支删除。')
add('N18','历史原型、消融及负结果','CPU PQ repair、同状态快照oracle、普通GPU frontier replay（I16）','oracle/replay保留；CPU生产执行器退休','冻结affected incoming及前后GPU state，CPU PQ求局部最短路验证距离/parent witness，普通GPU frontier replay识别工作放大；曾接生产CPU repair测完整handoff而非只看PQ。', [('include/framework/i16_repair_snapshot.h','struct '),('src/i16_repair_oracle.cpp','int main'),('src/i16_frontier_replay.cu','int main'),('archive:logs/i17_cpu_retirement/source_and_notes.tar.gz','include/framework/i16_cpu_repair.h')],f'{plan} I16索引；archive内iteration/i16_paired_and_cpu_assessment.md及logs/i16_paired_20260907/原日志。EU三批GPU339.325/351.754s、CPU93.263/93.533s，聚合-72.97%；USA GPU129.960/126.786s、CPU48.601/48.849s，-62.04%。logs/i16_cpu_pq_10batch_20260908/status.json已completed，两图各10次删除/批末distance检查通过；本轮另存i16_recovered_evidence.json。','这是相对当时GPU pull的真实完整正收益，不能因后来退休就改写成CPU路网实验失败；它不证明CPU硬件优于有序GPU。后续mechanism对TW/FS完整CPU/GPU比约4.24–4.28/1.92–2.32，显示明确regime边界；road准备约占service55%。当前未启用CPU路网repair，旧runner只适合冻结binary；不能把低直径owner负结果外推到这一结果。')
add('N19','历史原型、消融及负结果','reverse record workspace复用、几何扩容及统计瘦身消融（B5）','候选均撤回，保留归档','分别尝试省record分配、单map几何reserve、每source仅16B写统计；这些改变都要看完整服务，不能只看局部分配/容量下降。', [('logs/i17b5_20260911/b543_reverse_profile/source_geometric/dynamic_reverse_index.h',''),('logs/i17b5_20260909/b53_candidate/dynamic_reverse_index.h',''),(S,'std::vector<ChunkStoreBatchMetrics> apply_metrics')],'iteration/subiteration_file/i17b5_workspace_screen.md、i17b543_reverse_shards.md、i17b7_b5_progress_20260914.md。workspace完整均值+4.18%；geometric FS十批18.365s慢于64片15.173s；统计瘦身TW10M约19.1→22.5s。','三个独立候选，不把全部慢因归于malloc或NUMA；统计候选精确数组容量-92%不是总RSS收益。workspace/stat已撤回源码的具体历史位置不完整，冻结binary和日志存在。')
add('N20','历史原型、消融及负结果','ordered host cursor复用/倒序CSR构建消融（I17-B1）','独立replay模式，未选入最终候选','用CSR end offsets递减填边省A+1个uint64 cursor，代价是source内outgoing顺序改变；完整准备和释放仍计入。', [('src/i17a_delta_replay.cu','reuse')],'iteration/subiteration_file/i17b_gpu_cost_results.md。host可省EU158.2/USA95.0MiB，但前后多组service既改善也回退，未过稳定收益gate。','节省host数组空间不能推出整系统加速；当前生产ordered仍复制cursor，不能写成已应用此优化。')
add('N21','历史原型、消融及负结果','多删除位置复用与连续存活区间搬移（I21旧候选）','代码保留，默认关闭','规划时记录递增匹配offset，compact/rewrite复用位置，跳过未改变前缀，按存活区间memmove/memcpy；每批一份request-sized位置数组，无per-source vector。', [(U,'CG_REUSE_DELETE_POSITIONS'),(S,'std::unique_ptr<index_t[]> deletion_positions'),(S,'positions_for'),(S,'void CompactSourceInPlace')],'iteration/subiteration_file/i21_delete_positions_20260915.md。TW/FS10M少读38810767/96908378条，完整仅-0.76%/-0.51%，forward写入不变。','仅large生效；40MB/phase临时容量有成本；位置读取减少不等于存活边写入减少，也不是已完成块级拓扑重建。')
add('N22','历史原型、消融及负结果','thread/source cooperative插入调度（I22首候选）','代码保留，普通模式显式thread','在同一GPU设备循环中改为thread/source串行扫邻接，试图减低度source的128线程block开销。',[(F,'__global__ void RunThreadGpuClosure'),(F,'const bool thread_schedule')],'iteration/subiteration_file/i22_cggraph_scheduling_20260915.md。EU1M两批196.540→359.155s（+82.74%），insertion+93.21%，边处理仅-2.38%、waves不变。','明确否决，不是CGgraph完整CTA/IWB实现；该实验也没有否定IWB所有可能。后继是有序算法，不是继续线程粒度扫参。')
add('N23','历史原型、消融及负结果','并行稳定source radix（I21-B）','代码保留，默认关闭','复用mutation pool，逻辑连续分区局部histogram、bucket/partition前缀、并行稳定scatter，保持删除/插入顺序；不是新增线程池。',[(U,'CG_PARALLEL_SOURCE_RADIX'),(U,'if (parallel_radix_)')],'iteration/subiteration_file/i21_radix_tw_20260916.md。TW1M合并+并行radix组合1762.8825→1686.1625ms（-4.352%），两对1.842%/6.787%，未过gate。','组合对照不能宣称radix有独立净收益；这不同于已保留串行radix，默认关闭。')
add('N24','历史原型、消融及负结果','count-prefix-scatter bulk source/groups物化（I23）','代码保留，默认关闭','并行识别source边界、统计group/phase计数，prefix分配索引与destination数组并scatter，消除串行逐record append/扩容；保持逐元素输出语义。',[(U,'if (bulk_groups_)'),('src/i23_group_replay.cpp','int main'),('tests/i23_bulk_group_test.py','def ')],'iteration/subiteration_file/i23_bulk_groups_20260916.md。TW1M CPU物化37.98→11.32ms；完整原路径/仅合并/合并+bulk为1758.9835/1624.7085/1687.347ms，bulk对仅合并回退3.8554%。','不得把仅合并-7.6337%写成bulk收益；10M条件队列未执行；否决的是这个实现完整收益，非count-prefix-scatter技术的一般有效性。')
add('N25','历史原型、消融及负结果','并行稳定reverse destination radix（I25）','代码保留，默认关闭，性能否决','复用reverse worker pool，连续分区histogram/prefix/scatter；≥65536记录启用，已有source顺序继续省四遍，额外histogram约40KiB/20workers。', [('include/framework/effective_delta_sort.h','if (partitions > 1)'),(R,'CG_PARALLEL_REVERSE_RADIX')],'iteration/subiteration_file/i25_reverse_radix_20260917.md；logs/i25_reverse_radix_20260917/。TW10M完整10762.8765→10847.8605ms（+0.7896%）；sort省360.048ms但后续group/slots/merge增加。','不能单报sort -45.18%宣称系统优化成功；与source radix是不同排序对象，失败结论分别登记。')
add('N26','历史原型、消融及负结果','最后worker20→32与10M/100M容量机会评估','已完成筛查/分析；非新算法','在已固定large/merge/reverse64/NUMA0/cache2下仅变mutation workers；CPU机制探针测真实10M排序/合并，100M重复记录仅压力测试，记录patch/arena/reverse容量边界。', [('include/utils/fixed_worker_pool.h','class FixedWorkerPool'),(F,'CG_MUTATION_WORKERS'),('scripts/run_i21_publication.py','def ')],'iteration/subiteration_file/final_system_sweep_20260916.md、scaling_feasibility_10m_100m_20260916.md。TW1M1622.023→1558.158ms，FS1749.395→1748.111ms，单对。','不能把调核数作为独立算法创新；100M合法双系统数据/运行未完成；TW10M同cache2已有16GB成功，但不是所有图显存保证。')
add('T01','数据、测量与可复现实验','连通路网core/随机保护森林更新生成器与独立verifier（I16）','工具完成','规范化原始无向边、BFS前缀core兼顾delete/insert池、随机顺序Kruskal保护森林、现存/缺失池动态交换，双向展开；独立校验每批合法性与删除中间态连通，manifest/hash与硬链接共享底图。', [('src/connected_road_generator.cpp','int main'),('src/verify_connected_road_dataset.cpp','int main'),('scripts/generate_connected_road_datasets.py','def '),('tests/connected_road_generator_test.py','def ')],'iteration/subiteration_file/connected_road_dataset_generation.md。EU/USA×50/75/99p×10/100/1000K共18组180批通过；EU/USA50p source1可达26,156,568/13,127,169。','保护森林导致删除偏差，不是所有现存边均匀删除；v1保护BFS树不是正式v2。换数据恢复可达性不能计为算法加速。')
add('T02','数据、测量与可复现实验','source可达性扫描、真实batch大小纠正与规模数据准备','工具完成','扫描有效源点、重映射ID并冻结base/update/stream哈希；统计实际adds/deletes，使用同底图不同合法batch前缀，避免文件名100K实际只有20K；将零传播样本标为topology-only。', [('src/road_source_scan.cpp','int main'),('scripts/prepare_stage_twitter.py','def '),('scripts/prepare_i17_scaling.py','def '),('tests/i17_scaling_generator_test.py','')],'iteration/subiteration_file/pre_i17c_stage_matrix.md、i17b6_completed_analysis.md。TW dense ID source0只可达自身的扩展性结论撤回，改28512093后约23.16M可达。','生成/采样是实验基础设施，不是SSSP性能创新；source必须随ID mapping冻结，旧/新cohort不可直接相减。')
add('T03','数据、测量与可复现实验','插删比例嵌套候选池与192批双向拓扑oracle（I19）','工具与数据完成','WK/FS共用每图底图，10%–90%九比例、每批100K十批；合法occurrence删除与原图held-out插入池，嵌套前缀/确定seed；CPU只物化涉及source做forward/reverse精确replay。', [('src/i19_ratio_pool.cpp','int main'),('scripts/prepare_i19_ratios.py','def emit'),('src/i19_topology_replay.cpp','int main'),('include/utils/i19_edge_reader.h','')],'iteration/subiteration_file/i19_ratio_data_20260914.md、i19_complete_results_20260915.md。180比例批+12规模批oracle通过；18组全阶段GPU检查；42次GPU运行。','比例变化同时改变净边数/affected，不是相同工作量优化；CPU replay不含真实GPU publication/cache，不能和完整P0相减求GPU时间。')
add('T04','数据、测量与可复现实验','完整batch计时、阶段嵌套与真实工作放大量账本','当前测量基础','P0覆盖完整删除/插入/hotness/candidate/eviction/compact/load；拆group/prepare/preflight/apply/reverse/publication，统计实际匹配读、mutation读写、effective表示、overlay、alloc/retire；区分source_work范围与实际访问。',[(H,'[P0-TIMER][SSSP]'),(F,'[I19-WORK]'),(F,'[I20-WORK]'),(S,'struct ChunkStoreBatchMetrics'),('scripts/analyze_i19.py','def ')],'iteration/subiteration_file/i19_work_amplification_20260914.md、i19_profile_tables_20260915.md。TW/FS10M grouping+mutation占70.69%/69.46%；比例P0最大残差约0.0152%。','reverse Prepare含在preflight，Commit含在apply，不能重复相加；布局payload≠总CPU memcpy/DRAM流量，初始化/check/trace与性能样本分列。')
add('T05','数据、测量与可复现实验','显式CUDA payload通信计量与共享包装（B7）','诊断工具，默认关闭','链接器wrap cudaMemcpy/cudaMemcpyAsync，只统计成功返回请求大小，batch/stage/category/direction互斥归属，嵌套scope最内层记账；初始化/check单列，不额外设备同步。', [('include/utils/communication_meter.h','inline void Record'),('src/utils/communication_meter.cpp',''),('tests/communication_meter_test.cpp','int main'),('scripts/analyze_i17_communication.py','')],'iteration/subiteration_file/i17b7_b5_progress_20260914.md；tests/communication_meter_test.cpp。TW10M两个算法batch显式H2D429029668B、D2H167005320B（该冻结correctness运行按stage排除检查）。','异步成功提交不代表物理完成字节；不统计GPU kernel内部访问、完整CPU copy、Zero-Copy或动态库内部未wrap调用；未测不能写零。')
add('T06','数据、测量与可复现实验','整组PCIe粗粒度采样、对照资格检查与原版隔离适配','诊断工具完成；无正式通信胜负','共用整组开始/结束monotonic窗口，进程外NVML RX/TX采样积分；比较器验证输入hash、参数、GPU、batch和共同checksum，采样不足双方统一N/A；原版在独立源码副本接相同wrapper。', [('include/utils/communication_window.h','inline void Window'),('scripts/communication/sample_pcie.py','def summarize'),('scripts/communication/compare.py','def main'),('scripts/communication/prepare_baseline.py','def main')],'scripts/communication/README.md；logs/communication_audit_20260915/。约2s probe观测/请求比H2D1.061、D2H1.105、ZC read1.062；工具测试开关结果一致。','采样支持量级覆盖ZC但不是精确ZC计量，不能payload+PCIe相加，也不能相减当ZC；原版小图oracle失败/双方checksum不一致时已拒绝胜负。补查logs/communication_100k_20260915_0815/results.json：WK/FS/EU真实100K三组也均因原版与已检查当前checksum不同而失败，status=complete_with_failures，pairs全空；不是任务仍在后台或已取得通信胜负。')
add('T07','数据、测量与可复现实验','同状态repair capture、binary/source manifest、replay成本边界','当前诊断与独立工具','只在显式capture下收集affected/incoming/needed states及修复前后快照，临时文件成功后发布；replay分别记index/transpose/allocation/H2D/closure/parent/free，计入首次准备和释放。',[(F,'void SetRepairSnapshot'),(F,'const bool capture ='),('include/framework/i16_repair_snapshot.h',''),('scripts/run_i16_frontier_replay.py','def '),('scripts/run_i17a_sparse.py','def ')],'iteration/subiteration_file/i17b_gpu_cost_results.md；logs/i16_e2_capture_20260907/manifest.json。服务口径v2明确host/device释放和首次构建，55回归与6memcheck为历史已执行。','snapshot文件加载、独立oracle不等于生产handoff；source hash与binary hash需绑定，不可用当前源码重编译binary冒充历史已测对象。')
add('T08','数据、测量与可复现实验','GPU串行锁、外来占用检测、NUMA控制、ABBA/失败停止runner','工具完成','冻结binary/input/env与源点，独占GPU队列、检测外来进程只停止自身，超时终止进程组，保存状态和失败日志；固定CPU/memory NUMA0避免放置混杂，分开correctness与performance。', [('scripts/run_i17_target_check.py',''),('scripts/run_i19.py','def '),('scripts/run_i21_publication.py','def '),('scripts/run_i16_paired.py','def parse_performance')],'iteration/subiteration_file/i17b5_incoming_source_order_20260914.md、i24_tw10m_publication_20260917.md。未绑NUMA的TW10M ABBA17.650/18.520/18.689/22.705s暴露混杂。','runner能力不等于所有历史实验均遵守；最后worker sweep未冻结binary/锁的不足保留。NUMA配置属于实验控制，不是按图优化算法。')
add('T09','数据、测量与可复现实验','性能矩阵的有效性重审与拒绝伪加速','审计与报告完成','从冻结runs/comparison解析两系统完整窗口/样本数、共同结果指纹、阶段中位数对应原run、内存/OOM、无传播source、权重差异；把诊断耗时比与可发表speedup分开。', [('scripts/analyze_performance_matrix_20260912.py',''),('scripts/run_stage_pre_i17c.py','def '),('scripts/analyze_i17_target_pair.py','def ')],'iteration/subiteration_file/performance_matrix_20260912_review.md、performance_matrix_20260912_analysis/tables.md。190任务188通过runner判据，但22/22跨系统checksum mismatch，有效跨系统加速比0组。','不能引用27×/23×等诊断耗时比当论文主结果；不是证明原版一定错误，需对齐边权/批次/source/语义与独立oracle后再归因。')
errors=[]
def locate(spec):
    path,needle=spec
    if path.startswith('git:'):
        _,rev,p=path.split(':',2)
        data=subprocess.check_output(['git','show',rev+':'+p],cwd=ROOT,text=True)
        lines=[i for i,l in enumerate(data.splitlines(),1) if needle in l]
        if not lines: errors.append((path,needle));return f'`{rev}:{p}`（定位待复核：{needle}）'
        return f'`{rev}:{p}:{lines[0]}` / `{needle}`（用 `git show {rev}:{p}` 查看）'
    if path.startswith('archive:'):
        p=path[8:]
        if not (ROOT/p).exists():errors.append((p,'missing archive'))
        return f'[{p}]({ROOT/p})'+(f' 内 `{needle}`' if needle else '（历史日志目录；未找到独立实现源码，不能视为源码复现闭合）')
    p=ROOT/path
    if not p.exists(): errors.append((path,'missing')); return f'`{path}`（文件缺失）'
    text=p.read_text(errors='replace'); lines=[i for i,l in enumerate(text.splitlines(),1) if needle in l] if needle else [1]
    if not lines: errors.append((path,needle)); return f'[{path}]({p})（符号待复核：{needle}）'
    return f'[{path}:{lines[0]}]({p}:{lines[0]})'+(f' / `{needle}`' if needle else '')
for item in items:item['code_links']=[locate(x) for x in item['code']]
if errors:
    print('LOCATION ERRORS',json.dumps(errors,ensure_ascii=False,indent=2))
    raise SystemExit(1)
(OUT/'work_items.json').write_text(json.dumps(items,ensure_ascii=False,indent=2)+'\n')
intro='''# 系统优化工作量与论文证据总账（截至2026-09-17）

本报告按**现有代码事实和证据状态**整理研发工作，不将“新增代码”自动认定为有收益的优化，也不将本项目新增机制自动认定为相对文献的首次创新。论文 novelty 仍须在相关工作比较中论证。下文每个工作项都有当前源码位置、git历史位置或归档位置；找不到已删除实现源码的项目明确标为证据缺口，不虚构行号。条目粒度用于防漏，并不表示72个相互独立的论文贡献。

## 1. 基线、范围与核验方法

- 用户提供的 `../C-GpuStreamGraph-CG` 解析后就是当前仓库自身。旁边实际原版为 `../C-GpuStreamGraph`；本报告采用其提交 `7ffcb29` 的源码作内容基线，避开该目录未提交的 CMake 改动。若用户原指另一份优化前版本，需要再替换基线，当前假设已经明示。
- 当前 `HEAD=26939b7`，2026-09-07；大量 I16–I25 实现仍在工作区/未跟踪文件里，不能只审HEAD。完整git状态和原版/当前commit在 [baseline_manifest.json](baseline_manifest.json)。
- 当前仓库初始提交 `f527ba4` 已经有协同修改：framework原版2188行、init4572行。因此只算init→HEAD会漏掉早期CPU_HOME、proposal与shadow机制。本报告同时看原版→工作区、init→工作区以及全部11个提交。
- 输入包括主实施计划全部编号、`subiteration_file` 的37份Markdown报告、补充运行流程/进展文档、真实生产调用链、独立模型与测试、原版对应文件、历史提交和可找到的归档。计划/旧“下一步”不能作完成证明，重复编号按“编号＋机制＋日期”消歧。
- 进行了源码/符号定位、目录与归档成员核验，并从8组关键实验目录的63份含P0日志重新抽取逐批时间与最终checksum，结果见 [raw_log_recalculation.json](raw_log_recalculation.json)。其中包含检查/失败开发日志，仅做原始抽取；是否性能样本仍以manifest与对应报告判定，不能混算。
- 本轮没有修改系统实现，没有重新运行GPU、构建或大规模测试；“测试通过”均绑定历史报告/日志中的版本，绝不冒称本轮新跑。
- 时间单位、批数、cohort与基线逐项注明；除明示“原版”外，历史收益均为内部版本/资源/模式对照。不能把不同迭代百分比相加/相乘算总收益，不能重复相加嵌套timer。

## 2. 当前可支撑的论文主线

| 建议组织为论文贡献的主题 | 对应工作项 | 可写的核心内容 | 证据限制 |
|---|---|---|---|
| 源局部CPU权威拓扑与GPU稀疏可见性 | A01–A06 | 更新隔离、并行源规划/物化、连续邻接、epoch回收、紧凑patch及reader事件契约 | 并非全图多版本事务，也不是CPU/GPU共同传播；host pinned内存必须报告 |
| 一份权威有效变更驱动多消费者 | A07–A11、B04、B06–B09 | occurrence语义、forward/reverse一致性、批内共享规划、稳定顺序复用、目的端并行维护与有序publication | large/shards/merge是显式策略，多个子项只有组合/短配对证据 |
| 工作量受控的GPU增量修复 | B01–B03、B05、B10–B12 | compact affected失效、boundary incoming修复、added-edge seed、精确source设备闭包 | 有全V reset初始化、parent诊断与ticket边界，不是所有控制工作都O(affected) |
| 长传播下的有序删除/插入 | B13–B16 | affected局部有序删除、控制/队列复用、插入pending距离窗口降低重复边松弛 | 手动大直径模式；权重1..128；社交图不普遍获益；未完成正式全图重复验收 |
| 拓扑更新与hot cache一致性协同 | C01–C02 | producer-native局部cache patch、稳定resident保留、严格refresh gate及容量fallback | 原hot cache为继承；全量hotness/candidate仍存在；主要收益为历史screening |
| 机制选择、负结果与可复现证据 | N01–N26、T01–T09、C03–C10 | 为什么CPU应维护拓扑而非强制分传播；为何少通信/少排序/语义合并不必然加速 | 负结果只否决具体实现和已测cohort，不是所有相关算法的不可能性定理 |

线程池、radix、warp、METIS、SPSC、CUB、NUMA绑定等是标准工具或技术；可发表的重点是它们在本系统中解决的**动态语义、状态可见性、局部工作组织和完整成本问题**。把每个工具写成独立原创算法会削弱论文可信度。

## 3. 当前实际默认值与仍存在的边界

| 入口 | 当前真实行为 |
|---|---|
| CPU topology workers | 未指定时框架请求20；实际受硬件/实现限制 |
| CG_BATCH_MAINTENANCE | 默认regular；large显式；auto仅按请求总B≥1,000,000选择large |
| CG_REVERSE_SHARDS | 默认1；显式64 |
| CG_ORDERED_REPAIR | 默认关闭；值1同时选择有序删除和有序插入，覆盖遗留插入调度变量 |
| CG_INSERTION_SCHEDULE | 普通模式未设置为block；可显式thread/ordered；大直径模式优先 |
| CG_MERGE_PUBLICATION_SOURCES | 默认关闭；1启用已得到自身系统收益证据的线性合并 |
| CG_REUSE_DELETE_POSITIONS / CG_PARALLEL_SOURCE_RADIX / CG_BULK_SOURCE_GROUPS / CG_PARALLEL_REVERSE_RADIX | 默认关闭；属于保留但未推荐的候选，不等于源码已删除 |
| CPU propagation owner | 默认capacity0、空domain map；历史owner函数/flags仍在；CPU路网PQ执行器已归档 |
| cache | 继续原hotness排序/候选链＋touched patch/refresh gate；没有生产事件treap或extent allocator |

需要保留的容量/语义边界：source degree与ID为32位；SSSP当前统一权重规则 `(src+dst)%128+1`；candidate prefix在现有32位degree scan域内，不能外推超范围；ordered local映射按V初始化；reverse overlay未有长期compaction证据；patch staging按最大batch预留，100M会有容量问题；目前通过的是distance与存在性tight witness，完整stored-parent树未封板。新旧binary的大直径开关语义不同，复现实验必须核对实际schedule日志。

## 4. 逐项工作清单

下文“当前主路径”是机制存在并在默认相关流程可达，不自动表示每张图都有正式性能收益；“显式”不等于默认；“历史”保留研发归属，不计为当前正向加速。代码链接行号绑定本次工作区快照，代码哈希见附件。
'''
stats=json.loads((OUT/'diff_statistics.json').read_text())
statlines=['## 1.1 可量化代码工作量（不等于工时）\n','| 扫描范围 | 相对原版差异文件 | 新增文件 | 修改文件 | 当前行数 | 文本新增行 | 文本删除行 |','|---|---:|---:|---:|---:|---:|---:|']
for k,label in [('core','include/src/samples（含replay和数据工具）'),('tests','tests（含fixture）'),('tools_and_build','scripts/tools/root构建与辅助脚本')]:
    z=stats['groups'][k]
    statlines.append('| '+label+' | '+' | '.join(str(z[f]) for f in ['files','added_files','modified_files','current_lines','added_lines','removed_lines'])+' |')
statlines.append('\n排除第三方、build、data、logs生成物与本次报告；注释/格式变化仍计入文本diff，不能视为有效算法行数。额外两个inventory条目与原版相同、只与本仓库init不同，不算对原版创新。原版和init各有一个现已删除的同名备份 `samples/hybrid_sssp/hybrid_sssp copy.cu`，单列于 [deleted_baseline_files.json](deleted_baseline_files.json)，不计入上表删除行。详见 [diff_statistics.json](diff_statistics.json)。')
statlines.append('\n## 1.2 Git历史覆盖\n\n提交日期用于定位代码版本，不把相邻提交间隔换算工时；一个提交可能包含多个迭代，未提交I16–I25更不能靠commit数量计量。\n\n| 提交 | 日期（UTC） | 原始提交标题 | 审计用途 |\n|---|---|---|---|')
notes={'f527ba4':'已有CPU协同初始快照，非原版','e6bc406':'overlap/probe/packet分步原型','9b590a2':'GPU skip/dirty/merge机制','0e036c8':'packet机制统计归档','caf1fc2':'CPU-owned阶段冻结','ddd253b':'owner/双路径演进历史','7dec6b4':'C阶段前后内部基线定位','94a631d':'source-local chunk与发布阶段','6295b28':'E系列与后续cache/计算机制','6ef292c':'F/P及早期I阶段收口','26939b7':'I14有效拓扑与I15 hotness配对'}
for row in subprocess.check_output(['git','log','--reverse','--format=%h|%ad|%s','--date=short'],cwd=ROOT,text=True).splitlines():
    rev,date,title=row.split('|',2);statlines.append(f'| `{rev}` | {date} | {title} | {notes.get(rev, "版本定位")} |')
intro=intro.replace('## 2. 当前可支撑的论文主线','\n'.join(statlines)+'\n\n## 2. 当前可支撑的论文主线')
sections=[intro]
for group in dict.fromkeys(x['group'] for x in items):
    sections.append(f'### {group}\n')
    for x in items:
        if x['group']!=group:continue
        sections.append(f"#### {x['id']}｜{x['title']}\n\n**状态：{x['status']}。** {x['mechanism']}\n\n**代码位置：** "+'；'.join(x['code_links'])+f"。\n\n**实验/验证证据：** {x['evidence']}\n\n**论文边界：** {x['boundary']}\n")
sections.append('''## 5. 编号覆盖核对与未实施项

| 原迭代/阶段 | 本报告对应 | 当前判定 |
|---|---|---|
| 初始快照、Overlap、优化合并、D10/packet v1 | N01–N04 | 已有实现/历史消融；未漏掉init之前已纳入快照的代码 |
| 10.7–10.9、A、B1–B3 | B01–B03、B05、B11、N05、C06 | 从全点kickoff/CPU修复转向事件化GPU路径，owner部分负结果 |
| C1–C4、D1–D3 | A01–A06、C07 | C4回退和D阶段资源/性能修复均记录，C1是内部基线不是原版 |
| E0–E3 | N06–N08 | 分区、持久owner、事件并发均有实际工作，非最终胜出 |
| E4-A1/A2、E4-R1/R2/R3 | N09–N11、B04、B11–B12 | 两种依赖结构被否决；exact-source/sorted merge保留；planner为shadow |
| E5、F0/F1、P0 | N12、C01–C02、T04 | F2–F4没实施；cache patch保留 |
| I0/I1/I2/I3 | C06–C07、T04、T08 | I0诊断、I2六图、I3基线为工作；I1条件未成立，跳过，不计已实现新修复 |
| I4及I4-R1/R2/R3 | N13–N15、C01–C03 | touched-only原假设否决，extent原型撤回，事件树后续也否决 |
| I5/I6/I7/I8/I9/I10 | A02、A04–A06、C07、T04 | 多核/契约完成；I6是overlap合法性审计，未实施完整双版本流水 |
| I11/I12/I13 | N16–N17 | 模型通过、生产事务失败撤回、两阶段恢复 |
| I14/I15 | A07–A08、C03、N13–N14 | 有效批次/配对纠错保留；不是旧计划中“外部对照”的同名I15 |
| I16 | N18、T01、T07 | capture/oracle/frontier/replay/data完整工作；CPU路网生产路径退休 |
| I17-A/B | B13–B14、N20 | sparse/compact有序机制；cursor reuse未选入 |
| I17-B5.1/B5.3/B5.4.1/B5.4.3及后续B5 | A07、A10、B06–B10、N19 | workspace否决；phase-active、并行merge、shards、radix/order reuse、incoming、warp分别登记 |
| I17-B6/I17-C/I18 | B13–B16、T02、T07 | 删除ordered已实验接入；人工建议不等于已验证预测器；I18独立收口未完成 |
| I17-B7 | T05–T06 | 显式账本＋整组PCIe估计；无正式跨系统通信胜负 |
| I19 | T03–T04 | 数据、192批CPU、42次GPU与画像；不能计为新增SSSP算法 |
| I20 | A09 | 显式large共享plan，通过开发短性能；大图完整gate未新增 |
| I21旧位置复用 / 新A/B/C | N21、A11、N23 | 位置复用关闭；A合并保留；B无增量证据；计划C不能当已交付整体 |
| I22 thread/ordered / 后续10M迁移同编号 | N22、B15–B16、N26 | thread否决，ordered长传播保留；100M迁移未做 |
| I23/I24/I25、最后worker筛查 | N24、A11、N25–N26 | bulk否决、publication成立、reverse并行radix否决、worker仅单对 |

未交付不能写成贡献：跨batch双版本流水、已证明通用的自动CPU/GPU owner/planner、完整CPU exact-source full runtime、生产event-hotness index、长期reverse base整理、GPU IWB完整移植、100M合法双系统扩展性、全部图parent树修复、自动大直径预测器。它们中有设计或测试substrate，完成状态不得越级。

## 6. 论文数字的使用等级与纠错

| 数字 | 可以怎样使用 | 不可以怎样使用 |
|---|---|---|
| I8 TW/FS 29.9%/16.1%完整下降 | 1/20-worker同系统资源消融，3次中位数，绑定旧cohort | 当前最终系统对原版speedup |
| D3对C1 WK/TW/FS 5.7%/37.4%/31.5% | 早期拓扑架构阶段对内部C1的最终中位对照，保留Orkut负项 | 直接当当前版本相对原仓库结果 |
| F1-C0 TW完整-63.3% | 单次十批screening支持cache放大机制 | 已完成交错重复的正式主性能 |
| B5组合 TW1M -53.52%等 | 同NUMA单次基线/候选配对；候选另有重复越历史线 | 给三个子优化各自分配同一收益，或称双方三次中位 |
| I20 TW/FS10M -7.36%/-9.59% | 两轮正反开发配对均值，明确未补大图全阶段gate | 所有规模/比例普适收益 |
| I16 CPU PQ EU/USA -72.97%/-62.04% | 当时GPU pull/CPU PQ三批ABBA，另有十批distance正确性 | CPU普遍胜过GPU硬件，或当前仍启用CPU repair |
| I22 EU1M 4.62× | 同binary、两批block/ordered短测，局部独立oracle和最终checksum边界明示 | EU十批正式超过原版、所有图都有效、wave减少 |
| I24 TW10M -5.0896% | publication对当前系统有完整收益，两对均改善 | 正式原版胜出；两次均低于历史线 |
| I25 sort -45.18% | 减少局部sort却完整+0.7896%的负结果 | 推荐性能优化 |
| 2026-09-12 22组原/今耗时比 | 诊断图表，speedup留N/A，共同指纹22/22不一致 | 任何正式跨系统速度优势 |

文档纠错特别记录：**主计划I16索引把CPU路网交接概括为“不合算”过强**。本轮从退休tar和真实日志恢复EU/USA三批72.97%/62.04%完整正收益及十批distance检查；正确叙述是“相对无序pull有效、后转GPU有序并退休”，不是“所有CPU传播尝试都失败”。I23“仅publication合并”实际-7.6337%，“合并+bulk”才是-4.0726%；bulk相对仅合并+3.8554%。I24两对5.2830%/4.8942%满足“均改善且均值约5%”，却不满足runner旧字段“两对各≥5%”，不能混写。旧progress_report的I12–I15下一步早已失效。fable5中“任何CPU变体都失败”等强措辞应收窄到已测方案，不能当理论结论。

## 7. 仍存在的证据缺口

1. **原版身份假设**已明确；若真正基线不是旁边的C-GpuStreamGraph，需重做差分归属。
2. **当前未提交源码不是所有实验binary的源码**。本报告给代码现状和历史实验分别绑定，未来论文冻结必须保存整体源码与编译环境，不只HEAD。
3. **已删除原型的源码并非全部找回**。I12与CPU road有明确tar；early packet有git；部分extent/workspace/stat或linked生产接线只有日志/独立模型，不能宣称完全可复现。条目已明确说明，未用相似当前函数冒充已删除实现。
4. **共同正确性与公平外部结果尚未闭合**。22组矩阵结果指纹不匹配，I24只跨历史目标线边界，不能因此否认已有内部优化，也不能发布正式外部speedup。
5. **端到端正确性范围有差别**：大量小图独立Dijkstra、部分真实图全阶段Bellman、部分只check=false最终checksum、范围筛查甚至未检checksum，必须分层报告。
6. **当前全V初始化、长期overlay/arena、GPU共存峰值、stored-parent和ticket上限**都是真实边界，不因受影响传播很快而省略。
7. **工时不可从git反推**。能精确统计代码/模块/迭代/测试/实验样本，不能编造人月。新增/删除行数也不是有效创新数；标准库、第三方与生成产物不计原创。

## 8. 附件索引

- [工作项机器可读总账](work_items.json)：72项，机制、状态、源码、实验和边界。
- [工作项CSV](work_items.csv)：可导入表格进行论文筛选。
- [原版/当前git基线与工作区状态](baseline_manifest.json)。
- [源码文件差异覆盖表](code_inventory.md) 与 [SHA256/来源JSON](code_inventory.json)：覆盖当前一方源文件与工具；不是只看git tracked。
- [历史源码符号位置](historical_code_locations.json)：git精确revision/path/lines。
- [37份子报告逐份覆盖表](document_coverage.md)。
- [文档与日志引用可用性](document_evidence_inventory.json)：主计划＋37份子报告的hash及日志引用存在性；历史错误/通配路径原样记录，不视为全部已复现。
- [找回的I16配对/十批检查证据](i16_recovered_evidence.json)；归档文档解出副本在 `historical_notes/`，其旧下一步不作当前执行指令。
- [原始P0日志复算](raw_log_recalculation.json)：逐日志、逐batch、checksum，供数字追溯。

本报告是截至该工作区的**可核验工作量台账与写作依据**，不将覆盖核对等同于不存在任何未知遗漏。后续新增或找回历史artifact可按相同ID表追加；现有主线、负结果、工程修复与实验工作均有单独入口，避免只保留最终成功机制而丢失研究过程。
''')
(OUT/'系统优化工作量与论文证据总账.md').write_text('\n'.join(sections))
with (OUT/'work_items.csv').open('w',newline='',encoding='utf-8-sig') as f:
    w=csv.writer(f);w.writerow(['ID','类别','工作/机制','状态','机制说明','代码位置','实验/验证证据','边界'])
    for x in items:w.writerow([x[k] for k in ['id','group','title','status','mechanism']]+['; '.join(x['code_links']),x['evidence'],x['boundary']])
inv=json.loads((OUT/'code_inventory.json').read_text())
lines=['# 源码与工具差分覆盖附表\n','基线为原版提交7ffcb29；当前为2026-09-17工作区。只列扫描目录中相对原版或init有差别的文件；不把行数当人月或创新数。第三方依赖、build/data/logs生成文件不纳入此表；历史删除机制由主报告git/tar条目覆盖。脚本temp目录包含实验runner，也计为工具工作。\n','| 文件 | 当前行数 | 对原版HEAD | 对本仓库init | git tracked |','|---|---:|---|---|---|']
for x in inv:lines.append(f"| [{x['path']}]({ROOT/x['path']}) | {x['lines']} | {x['original_head_status']} | {x['init_status']} | {x['tracked']} |")
(OUT/'code_inventory.md').write_text('\n'.join(lines)+'\n')
# Archive membership and every local source link are checked independently of report prose.
import tarfile
archive_checks=[]
for x in items:
    for path,needle in x['code']:
        if path.startswith('archive:') and needle:
            p=ROOT/path[8:]
            with tarfile.open(p) as t:
                matches=[m for m in t.getnames() if m.lstrip('./')==needle]
            assert matches,(path,needle)
            archive_checks.append({'id':x['id'],'archive':str(p),'member':needle,'exists':True})
(OUT/'archive_member_checks.json').write_text(json.dumps(archive_checks,ensure_ascii=False,indent=2)+'\n')
print('GENERATED',len(items),'items',len(inv),'inventory files',len(archive_checks),'archive members checked')
